### ISSUE TITLE
go-chassi compatibility issue with istio 1.0.0

### ISSUE THREAD

**Issue by savitaashture** [go-chassis/go-chassis#357]
Deployed client and server using **pilot** service discovery.

1. Once application is in running state executed curl request to the client 
```
curl http://127.0.0.1:30107
lb: FindMicroServiceInstances failed, ProviderID: server-mesher, err: GetHostsByKey http://istio-pilot.istio-system:8080/v1/registration/server-mesher.chassis123.svc.cluster.local|http|app=default failed, response StatusCode: 404, response body: 404: Page Not Found
```
2. executed curl request for the pilot
```
curl http://istio-pilot.istio-system:8080/v1/registration/server-mesher.chassis123.svc.cluster.local%7Chttp%7Capp=default

404: Page Not Found
```

**Comment by tianxiaoliang** [comment]
now only support istio 0.8 will upgrade to 1.0

**Comment by crystaldust** [comment]
@savitaashture Since Istio 1.0.0 removes the xDS v1 APIs, we can only fetch the service info by xDS v2 API which is based on gRPC.
While in Istio 1.0.0, there is still a set of debug APIs to fetch service info, like:
http://istio-pilot.istio-system:8080/debug/adsz   To get the aggregated resources
http://istio-pilot.istio-system:8080/debug/cdsz   To get the clusters

Details could be found [here](https://github.com/istio/istio/tree/release-1.0/pilot/pkg/proxy/envoy/v2)

We'll support xDS v2 APIs in the future release.

**Comment by savitaashture** [comment]
@crystaldust

**Comment by crystaldust** [comment]
@savitaashture Istio 1.0 support is now ready, you can refer to the documents [here](https://mesher.readthedocs.io/en/latest/istio/discovery.html?highlight=pilot), and there is an [example of using Istio 1.0 as control](https://github.com/go-mesh/mesher-examples/tree/master/pilotv2-example)

**Comment by tianxiaoliang** [comment]
also need guides for go chassis
